---
title: "SVI_map"
author: "Christine"
date: "10/15/2020"
output: html_document
---
```{r,echo=FALSE,include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE,fig.width=12, fig.height=8)
library(dplyr)
library(leaflet)
library(purrr)
library(sf)
library(mapview)
library(raster)
library(geojsonio)
library(stars)
library(stringr)
library(leafpop)
load('./Build/Index/SVI.RData')
load('./Build/Index/SVI_comp.RData')
SVI_comp<-SVI_comp%>%
  dplyr::select(census_block_group,qualify_before,flip_before,qualify)
load('./Build/Data/state_08.rdata')


delist<-function(geog){
  geog%>%
    rename(census_block_group=geoid)%>%
  dplyr::left_join(.,SVI_comp) 
}
SVI_layer<-st_out%>%
  map_dfr(.,delist)%>%
  st_set_crs(4269)%>%
  #st_transform("+proj=longlat +datum=WGS84")%>%
  na.omit()%>%
  left_join(SVI)
rm(SVI,st_out,SVI_comp)
pal<-colorQuantile("Reds",na.omit(SVI_layer$overall_rank))
pal_binary<-colorFactor(palette=c('purple','steelblue','red'), domain=c(-1,0,1))
load('./Build/Cache/SVI_dat.RData')
weight<- c(1.25,.75,1.25,.75,.5,.5,.5,.5,1.25,1,0,1,0,.25,0,1.25,1.25)
weights<-data.frame(c(names(SVI_dat%>%dplyr::select(-census_block_group,-WUI))),
                    c('socioeconomic','socioeconomic','socioeconomic','socioeconomic'
                      ,'Household Composition/Disability','Household Composition/Disability','Household Composition/Disability','Household Composition/Disability'
                      ,'Minority Status/Language','Minority Status/Language'
                      ,'Housing/Transportation','Housing/Transportation','Housing/Transportation','Housing/Transportation','Housing/Transportation'
                      ,'Equity','Equity'),
                    weight/sum(weight))
names(weights)<-c('variable','category','weight')
rm(SVI_dat)
```



```{r WUI recut, echo=FALSE,include=TRUE}
variables<-weights%>%
  dplyr::filter(weight!=0)%>%
  dplyr::select(variable)
SVI_pop<-SVI_layer%>%
  dplyr::select(overall_rank,variables$variable)%>%
  mutate(across(is.numeric,round,3))%>%
  mutate(across(is.numeric,~100*.x))%>%
  mutate(across(is.numeric & !median_hh_income_3 & !gini_education & !gini_income & !overall_rank,paste,"%"),.keep="all")%>%
  mutate(across(overall_rank,str_replace,'^0$',"Non-WUI"),.keep="unused")%>%
  mutate(across(median_hh_income_3,~.x/100),.keep="unused")%>%
  mutate(across(median_hh_income_3,paste,'USD'),.keep="unused")%>%
  rename('SVI Rank'=overall_rank,
         'Below Poverty Line'=poverty_percent_below_1,
         'Labor Force Unemployed'=civ_labor_force_unemployed_percent_2,
         'Median Household Income'=median_hh_income_3,
         'Adults without HS Diploma'=no_hs_degree_percent_4,
         'Income GINI'=gini_income,
         'Education GINI'=gini_education,
         'Disabled Adults'=disabled_adult_percent_7,
         'Single Parent Households'=single_householder_percent_8,
         'Minority status'=percent_minority_9,
         'Do not speak English well'=do_not_speak_english_well_percent_10,
         'Homes that are mobile homes'=units_mobile_percent_12,
         'Over 65'=over_65_percent_5,
         'Under 18'=under_18_percent_6,
         'Households without vehicle'=no_vehicle_percent_14,
         #'Percent housing units that are apartments'=units_over_10_percent_11,
        # 'Percent housing units that are crowded'=over_1_person_room_percent_13
         )
  
map<-leaflet(SVI_layer)%>%
  addTiles()%>%
  addPolygons(color = "#444444",weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.6,fillColor = ~pal_binary(qualify),
     group="Augmented SVI",
   popup = popupTable(SVI_pop,zcol=c("SVI Rank","Below Poverty Line","Labor Force Unemployed","Median Household Income","Adults without HS Diploma","Over 65","Under 18","Disabled Adults","Single Parent Households","Minority status" ,"Do not speak English well","Homes that are mobile homes","Households without vehicle","Income GINI"   ,"Education GINI"),row.numbers=FALSE,feature.id = FALSE),
   popupOptions = popupOptions(width=300,height=400, keepInView = TRUE,closeOnClick = TRUE),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE)) %>%
  addLegend(position="bottomright",
             colors=c('steelblue','red'),
            labels=c('does not qualify','does qualify'),
            values = ~qualify_state.x,
    title = "SVI",
    opacity=.6)%>%
  addLayersControl(
    overlayGroups = c("Augmented SVI"),
    options = layersControlOptions(collapsed = FALSE))%>%
      hideGroup(c("Augmented SVI"))
map
```