---
title: "Updating Reduced Match Criteria for the Forest Restoration & Wildfire Risk Mitigation Grant"
author: "Innocent Vomitadyo and Jude Bayham"
date: last-modified
date-format: "[Updated] MMMM, YYYY"
format: 
  html:
      toc: TRUE
      embed-resources: true
      page-layout: full
---

## Introduction

In 2020, our research team at Colorado State University developed the [Wildfire Social Vulnerability Index](https://jbayham.github.io/CSFS_WSVI/report.html) (WFSVI) in order to set a criteria for reduced match for the Forest Restoration & Wildfire Risk Mitigation (FRWRM) Grant. This report describes updates to the WFSVI including updated data from the US Census, alignment with the CO [HB21-1266](https://leg.colorado.gov/sites/default/files/2021a_1266_signed.pdf) EnviroScreen tool, and further analysis of the WFSVI and reduced match criteria. The number of census block groups qualifying for reduced match has increased due to updated data and the inclusion of *disproportionately impacted communities* information from CO EnviroScreen.



## American Community Survey Update

The original WFSVI was built using 5-year (2016 - 2020) [American Community Survey](https://data.census.gov/) (ACS) estimates. We have updated the WFSVI using the most current 5-year (2017-2021) ACS data. In some cases, no data is reported for a census block group because of poor response to the ACS or insufficient sample size to meet data disclosure requirements.  We use two methods to impute missing values.  First, if the data is reported at the census tract^[Multiple block groups are [nested within tracts](https://www2.census.gov/geo/pdfs/reference/geodiagram.pdf).], we use the census tract data to fill any missing records. While these data may be less spatially accurate, they represent the next best estimate of the block group value.  Second, we use a machine learning imputation model to complete missing records when tract level information is unavailable. The machine learning method is known as random forest and is implemented via [missForest](https://github.com/stekhoven/missForest) package in R. The random forest method uses nonmissing data for one variable to train a model based on other nonmissing variables from other block groups around the state and uses that model to estimate missing values. It applies this procedure to each variable and iteratively updates until the model converges on its best estimate (see the [package documentation](https://github.com/stekhoven/missForest) for more information).  

The original WFSVI used ACS data but sourced the data from [Safegraph](https://www.safegraph.com/free-data/open-census-data). While the data was accurate, it was less accessible and relied on analysts at SafeGraph to update the data when the Census released new data. We have rebuilt the code to access the Census Application Programming Interface (API) via the [tidycensus](https://walker-data.com/tidycensus/) package. The [code](https://github.com/jbayham/CSFS_WSVI/blob/master/Build/Code/01_get_data.R) now downloads data for the Census Block Groups (CBG) and Census Tracts, then calculates the index component for both geographies using tract information to fill in missing block group information. The user can now define the year from which to query census data, making the layer easy to update in the future.


## Colorado EnviroScreen Data

Colorado’s Environmental Justice Act ([HB21-1266](https://leg.colorado.gov/sites/default/files/2021a_1266_signed.pdf)) prompted the development of the [EnviroScreen](https://teeo-cdphe.shinyapps.io/COEnviroScreen_English/) mapping tool to identify "disproportionately impacted communities". We consider any disproportionately impacted community to automatically qualify for the FRWRM reduced match requirement. According to the EnviroScreen documentation, a disproportionately impacted community is defined as

> ... census block groups where more than 40% of the population are low-income (meaning that median household income is at or below 200% of the federal poverty line), 50% of the households are housing cost-burdened (meaning that a household spends more than 30% of its income on housing costs like rent or a mortgage), 40% of the population are people of color (including all people who do not identify as non-Hispanic white), or 20% of households are linguistically isolated (meaning that all members of a household that are 14 years old or older have difficulty with speaking English). Also included in this definition are mobile home communities, the Ute Mountain Ute and Southern Ute Indian Reservations, and all areas that qualify as disadvantaged in the federal [Climate and Economic Justice Screening Tool](https://screeningtool.geoplatform.gov/en/#3/33.47/-97.5). The definition also includes census block groups that experience higher rates of cumulative impacts, which is represented by an EnviroScreen Score (Percentile) above 80.

The CO EnviroScreen tool data was built using 5-year ACS data from 2015-2019 along with many other data sources. The challenge is that this updated uses data from the 5-year ACS 2017-2021, which are based on census block groups redefined in 2020. Consequently, the CO EnviroScreen tool data cannot be directly merged with the WFSVI data. We use a geographic crosswalk designed to harmonize data across time (Manson et al., 2021). The crosswalk develops a set of weights based on the estimated fraction of the population or households in the 2010-2020 block group definition to the 2020 block group definition. We use the population weights to translate the following data between block group definitions: the low-income, people of color, the cumulative impact score, and the Justice 40 criteria, and the household weights to map the housing burden and linguistic isolation criteria. We then apply the qualifying thresholds defined above to determine which of the 2020 block groups qualifies as a disproportionately impacted community. 

The integration of the CO EnviroScreen tool aligns the WFSVI with HB21-1266 in Colorado and the federal Justice 40 initiative.


## Analysis

Data from the ACS is sampled with uncertainty. We develop a method to investigate how the uncertainty affects the qualifying classification of a particular block group. A margin of error is reported for each variable (component of the WFSVI) in each block group. We use the margin of error to estimate the standard deviation of the reported estimate.  We define a normal sampling distribution with the estimate as the mean and its standard deviation for each census variable for each block group. We then conduct a Monte Carlo simulation by sampling values from each distribution and recomputing the WFSVI. We run 1000 simulations and calculate the fraction of simulations that a block group qualifies based on its WFSVI above the 75th percentile cutoff. For example, a block group may qualify for reduced match in every one of the 1000 simulations indicating strong confidence that that block group indeed should qualify. In contrast, a block group that only qualifies 50% of the time suggests less confidence that it should qualify. The simulation is conducted in the script [07_monte_carlo_simulation.R](https://github.com/jbayham/CSFS_WSVI/blob/master/Build/Code/07_monte_carlo_simulation.R).


## Updated WFSVI Layer

```{r}
#| echo: false
#| fig-height: 8


suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(sf,quietly = T))
suppressPackageStartupMessages(library(leaflet,quietly = T))
suppressPackageStartupMessages(library(scales,quietly = T))

#Read data
sim_results <- readRDS("../Build/Cache/final_simulated_results.rds") 

wfsvi_coes <- readRDS('../Build/Output/wfsvi_coes.rds') %>%
  st_transform(4326) %>%
  mutate(q_indicator=ifelse(qualifying_cbg==1,"Qualifying","Not Qualifying"),
         coes_DIC=ifelse(coes_DIC==1,T,F),
         across(c(poverty_percent_below_1_rank:wfsvi),~round(.,digits = 2))) %>%
  #inner_join(select(sim_results,GEOID,percent_qualify)) 
  inner_join(sim_results,by = "GEOID") 


#save layer
out <- wfsvi_coes %>%
  select(block_group=GEOID,
         poverty_percent_below_1_rank:directional_median_hh_income_3_rank,
         wfsvi,percent_qualify,
         COES_DIC=coes_DIC,
         reduced_match_qualify=q_indicator) 



st_write(out,"wfsvi_2023.gpkg",append=FALSE,quiet = TRUE)
suppressWarnings(st_write(out,"wfsvi_2023.shp",append=FALSE,quiet = TRUE))
zip(zipfile="wfsvi_2023_shp.zip",files = c("wfsvi_2023.dbf","wfsvi_2023.prj","wfsvi_2023.shp","wfsvi_2023.shx"))
write_csv(st_set_geometry(out,NULL),"wfsvi_2023.csv")

out_qualify_only <- out %>%
  select(block_group,reduced_match_qualify)

st_write(out_qualify_only,"reduced_qualify_2023.gpkg",append=FALSE,quiet = TRUE)
suppressWarnings(st_write(out_qualify_only,"reduced_qualify_2023.shp",append=FALSE,quiet = TRUE))
zip(zipfile="reduced_qualify_2023_shp.zip",
    files = c("reduced_qualify_2023.dbf","reduced_qualify_2023.prj","reduced_qualify_2023.shp","reduced_qualify_2023.shx"))
write_csv(st_set_geometry(out_qualify_only,NULL),"reduced_qualify_2023.csv")



#Set color scale
color_scale <- colorFactor(palette = "viridis",domain = c("Qualifying","Not Qualifying"))

#################
# Create the map
#map <- leaflet(data = slice_sample(wfsvi_j40,n=200)) %>%
map <- leaflet(data = wfsvi_coes) %>%
  addTiles() %>%
  setView(lng = -105.5509, lat = 39.5501, zoom = 7)  # Set initial map view to Colorado

# Add census block groups as polygons
map <- map %>%
  addPolygons(group = "qualifying",
              fillColor = ~color_scale(q_indicator), 
              fillOpacity = 0.4,
              color = "white", 
              weight = 1,
              popup = ~paste0("<b>Block Group ID:</b> ", GEOID,
                              "<br><b>WFSVI:</b> ", wfsvi,
                              "<br><b>Qualifying Frequency:</b> ", percent(percent_qualify,accuracy=1),
                              "<br><b>CO Disp. Imp. Comm.:</b> ", coes_DIC,
                              "<br><b>Poverty (12%):</b> ", poverty_percent_below_1_rank,
                              "<br><b>Unemployed (7%):</b> ", civ_labor_force_unemployed_percent_2_rank,
                              "<br><b>Household Income (12%):</b> ", directional_median_hh_income_3_rank,
                              "<br><b>Education (7%):</b> ", no_hs_degree_percent_4_rank,
                              "<br><b>Over 65 (2%):</b> ", over_65_percent_5_rank,
                              "<br><b>Under 18 (2%):</b> ", under_18_percent_6_rank,
                              "<br><b>Disability (2%):</b> ", disabled_adult_percent_7_rank,
                              "<br><b>Single-parent Family (2%):</b> ", single_householder_percent_8_rank,
                              "<br><b>Minority (12%):</b> ", percent_minority_9_rank,
                              "<br><b>English-speaking (5%):</b> ", eng_proficiency_rank,
                              "<br><b>Mobile Housing (5%):</b> ", mobile_units_rank,
                              "<br><b>No Vehicle (2%):</b> ", no_vehicle_percent_14_rank,
                              "<br><b>Income Inequality (12%):</b> ", Gini_income_rank,
                              "<br><b>Education Inequality (12%):</b> ", Gini_education_rank))

map <- map %>%
  addLegend("bottomright", pal = color_scale, values = c("Qualifying","Not Qualifying"),
            title = NULL) %>%
  addLayersControl(
    overlayGroups = c("qualifying"),
    options = layersControlOptions(collapsed = TRUE)
  )

#print map
map

```

The interactive map shows census block groups that qualify for reduced match in yellow. The user can zoom into any location and click on block groups for more information.  The popup contains the block group identifying number, the WFSVI value, the qualifying frequency described above, whether it qualifies because of its "disproportionately impacted community" designation, and the value of each WFSVI component. The index is described in more detail in the [original report](report.html). The WFSVI and its components are all displayed in percentiles of the distribution of all values in Colorado block groups. The higher the value, the more likely the block group is to qualify for the reduced match. The percentage reported for each index component represents the weight of the component in the overall WFSVI. Note that the percentages are rounded and may not add to one

You can download spatial and non-spatial version of the layer containing the reduced match qualifying indicator here:

- [reduced_qualify_2023_shp.zip](reduced_qualify_2023_shp.zip) 

- [reduced_qualify_2023.gpkg](reduced_qualify_2023.gpkg) 

- [reduced_qualify_2023.csv](reduced_qualify_2023.csv)


The following files include the indicator for reduced match and the underlying data:

- [wfsvi_2023_shp.zip](wfsvi_2023_shp.zip) 

- [wfsvi_2023.gpkg](wfsvi_2023.gpkg) 

- [wfsvi_2023.csv](wfsvi_2023.csv)



## Limitations

American Community Survey data is based on a sample with a reported margin of error. The COVID-19 pandemic impacted trends and affected the ability to collect data due to sampling challenges. The [U.S. Census Bureau reported](https://www.census.gov/newsroom/blogs/random-samplings/2021/10/pandemic-impact-on-2020-acs-1-year-data.html) that, due to the difficulties of fielding a household survey during the COVID-19 pandemic, household nonresponse increased substantially in the ACS, with evidence of increased nonresponse bias in many statistics. These challenges largely apply to the 1-year ACS estimates and are less of a concern for the 5-year estimates. However, these inaccuracies and high margins of errors may lead to inaccurate classifications. It may take some time before the full impact of the pandemic on census data accuracy is fully understood. It is also important to note that the margin of error may be significant in small census block groups. We acknowledge the potential that the data may be inaccurate. However, the ACS is the most reliable data to calculate the WFSVI. 

## References

Steven Manson, Jonathan Schroeder, David Van Riper, Tracy Kugler, and Steven Ruggles.
IPUMS National Historical Geographic Information System: Version 16.0 [dataset].
Minneapolis, MN: IPUMS. 2021. http://doi.org/10.18128/D050.V16.0

